; 大模型 - 设置极大上下文使其难以被驱逐（占用资源多）  模型默认上下文
[conf-big-code]
model = /data/ai/models/gguf/MiniMax-M2.5-UD-Q4_K_XL.gguf
alias = big-code
cpu-moe=true
ctx-size=32768
temp=1.0
top-p=0.95
min-p=0.01
top-k=40
chat-template-kwargs="{\"enable_thinking\": false}" 

[conf-big-math]
model = /data/ai/models/gguf/step3p5_flash_Q4_K_S.gguf
alias = big-math
cpu-moe=true
ctx-size=133120
temp=1.0
top-p=0.95
min-p=0.01
top-k=40 

; 小模型A - 轻量级配置
[conf-small-agent]
model = /data/ai/models/gguf/GLM-4.7-Flash-UD-Q4_K_XL.gguf
alias = small-router
cpu-moe=true
ctx-size=32768
temp=0.7
top-p=1.0
min-p=0.01

; 小模型B - 轻量级配置
[conf-small-zh]
model = /data/ai/models/gguf/Qwen3.5-35B-A3B-UD-Q4_K_XL.gguf
alias = small-zh
cpu-moe=true
ctx-size=32768
temp = 0.6
top-p=0.95
top-k=20
min-p=0.0
